language: cpp
compiler: gcc
os: linux

before_install:
  - sudo apt-get update --quiet
  - bash <(curl https://nixos.org/nix/install)


before_script:
  - sudo apt-get install cmake3

script:
- cmake . && make
- tar -cvzf package.tar.gz vacuum
- rm ./vacuum
- tar -xvzf package.tar.gz
- ./vacuum

