language: cpp
compiler: gcc
os: linux

before_install:
  - sudo apt-get update --quiet
  - bash <(curl https://nixos.org/nix/install)
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh


before_script:
  - sudo apt-get install cmake3

script:
- nix-env --version
- nix-env -f ./default.nix -qa
- cmake . && make
- tar -cvzf package.tar.gz vacuum
- rm ./vacuum
- tar -xvzf package.tar.gz
- ./vacuum
