language: nix
compiler: gcc
os: linux

before_install:
  - sudo apt-get update --quiet

before_script:
  - sudo apt-get install cmake3

script:
  - source $HOME/.nix-profile/etc/profile.d/nix.sh
  - nix-env --version
  - nix-env -q
  - nix-shell
  - cmake . && make
  - tar -cvzf package.tar.gz vacuum
  - rm ./vacuum
  - tar -xvzf package.tar.gz
  - ./vacuum
